// Code generated by mockery. DO NOT EDIT.

//go:build !release

package commands

import (
	context "context"
	networking "word-of-wisdom-go/internal/services/networking"

	mock "github.com/stretchr/testify/mock"
)

// MockCommandHandler is an autogenerated mock type for the CommandHandler type
type MockCommandHandler struct {
	mock.Mock
}

type MockCommandHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandHandler) EXPECT() *MockCommandHandler_Expecter {
	return &MockCommandHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: ctx, con
func (_m *MockCommandHandler) Handle(ctx context.Context, con networking.Session) error {
	ret := _m.Called(ctx, con)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, networking.Session) error); ok {
		r0 = rf(ctx, con)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockCommandHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - con networking.Session
func (_e *MockCommandHandler_Expecter) Handle(ctx interface{}, con interface{}) *MockCommandHandler_Handle_Call {
	return &MockCommandHandler_Handle_Call{Call: _e.mock.On("Handle", ctx, con)}
}

func (_c *MockCommandHandler_Handle_Call) Run(run func(ctx context.Context, con networking.Session)) *MockCommandHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(networking.Session))
	})
	return _c
}

func (_c *MockCommandHandler_Handle_Call) Return(_a0 error) *MockCommandHandler_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandHandler_Handle_Call) RunAndReturn(run func(context.Context, networking.Session) error) *MockCommandHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommandHandler creates a new instance of MockCommandHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandHandler {
	mock := &MockCommandHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
