dir: "{{.InterfaceDirRelative}}"
inpackage: true
filename: "mock_{{.InterfaceNameSnake}}.go"
mockname: "mock{{ .InterfaceName | camelcase }}"
mock-build-tags: "!release"
disable-version-string: true
packages:
  word-of-wisdom-go/internal/app:
    config:
      filename: "{{.InterfaceNameSnake}}.go"
      mockname: "{{ .InterfaceName | camelcase }}"
    interfaces:
      mockRequestRateMonitor:
      mockChallenges:
      mockWowQuery:
  log/slog:
    interfaces:
      Handler:
        config:
          inpackage: false
          outpkg: 'diag'
          dir: 'internal/diag'
          filename: "mock_slog_handler.go"
          mockname: MockSlogHandler