dir: "{{.InterfaceDirRelative}}"
inpackage: true
filename: "mock_{{.InterfaceNameSnake}}.go"
mock-build-tags: "!release"
disable-version-string: true
packages:
  word-of-wisdom-go/pkg/app/challenges:
    interfaces:
      RequestRateMonitor:
      Challenges:
  word-of-wisdom-go/pkg/app/wow:
    interfaces:
      Query:
  log/slog:
    interfaces:
      Handler:
        config:
          inpackage: false
          outpkg: 'diag'
          dir: 'pkg/diag'
          filename: "mock_slog_handler.go"
          mockname: MockSlogHandler