dir: "{{.InterfaceDirRelative}}"
inpackage: true
filename: "mock_{{.InterfaceNameSnake}}.go"
mockname: "mock{{ .InterfaceName | camelcase }}"
mock-build-tags: "!release"
disable-version-string: true
packages:
  word-of-wisdom-go/cmd/client:
    interfaces:
      challengesService:
  word-of-wisdom-go/internal/api/tcp/server:
    interfaces:
      commandHandler:
  word-of-wisdom-go/internal/api/tcp/commands:
    interfaces:
      requestRateMonitor:
      challengesService:
      wowQuery:
  log/slog:
    interfaces:
      Handler:
        config:
          inpackage: false
          outpkg: 'diag'
          dir: 'internal/diag'
          filename: "mock_slog_handler.go"
          mockname: MockSlogHandler