// Code generated by mockery. DO NOT EDIT.

//go:build !release

package wow

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockQuery is an autogenerated mock type for the Query type
type MockQuery struct {
	mock.Mock
}

type MockQuery_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuery) EXPECT() *MockQuery_Expecter {
	return &MockQuery_Expecter{mock: &_m.Mock}
}

// GetNextWoW provides a mock function with given fields: ctx
func (_m *MockQuery) GetNextWoW(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetNextWoW")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuery_GetNextWoW_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextWoW'
type MockQuery_GetNextWoW_Call struct {
	*mock.Call
}

// GetNextWoW is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuery_Expecter) GetNextWoW(ctx interface{}) *MockQuery_GetNextWoW_Call {
	return &MockQuery_GetNextWoW_Call{Call: _e.mock.On("GetNextWoW", ctx)}
}

func (_c *MockQuery_GetNextWoW_Call) Run(run func(ctx context.Context)) *MockQuery_GetNextWoW_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQuery_GetNextWoW_Call) Return(_a0 string, _a1 error) *MockQuery_GetNextWoW_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuery_GetNextWoW_Call) RunAndReturn(run func(context.Context) (string, error)) *MockQuery_GetNextWoW_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuery creates a new instance of MockQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuery {
	mock := &MockQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
