// Code generated by mockery. DO NOT EDIT.

//go:build !release

package main

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockChallengesService is an autogenerated mock type for the challengesService type
type mockChallengesService struct {
	mock.Mock
}

type mockChallengesService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockChallengesService) EXPECT() *mockChallengesService_Expecter {
	return &mockChallengesService_Expecter{mock: &_m.Mock}
}

// SolveChallenge provides a mock function with given fields: ctx, complexity, challenge
func (_m *mockChallengesService) SolveChallenge(ctx context.Context, complexity int, challenge string) (string, error) {
	ret := _m.Called(ctx, complexity, challenge)

	if len(ret) == 0 {
		panic("no return value specified for SolveChallenge")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, string) (string, error)); ok {
		return rf(ctx, complexity, challenge)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, string) string); ok {
		r0 = rf(ctx, complexity, challenge)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, string) error); ok {
		r1 = rf(ctx, complexity, challenge)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockChallengesService_SolveChallenge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SolveChallenge'
type mockChallengesService_SolveChallenge_Call struct {
	*mock.Call
}

// SolveChallenge is a helper method to define mock.On call
//   - ctx context.Context
//   - complexity int
//   - challenge string
func (_e *mockChallengesService_Expecter) SolveChallenge(ctx interface{}, complexity interface{}, challenge interface{}) *mockChallengesService_SolveChallenge_Call {
	return &mockChallengesService_SolveChallenge_Call{Call: _e.mock.On("SolveChallenge", ctx, complexity, challenge)}
}

func (_c *mockChallengesService_SolveChallenge_Call) Run(run func(ctx context.Context, complexity int, challenge string)) *mockChallengesService_SolveChallenge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(string))
	})
	return _c
}

func (_c *mockChallengesService_SolveChallenge_Call) Return(_a0 string, _a1 error) *mockChallengesService_SolveChallenge_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockChallengesService_SolveChallenge_Call) RunAndReturn(run func(context.Context, int, string) (string, error)) *mockChallengesService_SolveChallenge_Call {
	_c.Call.Return(run)
	return _c
}

// newMockChallengesService creates a new instance of mockChallengesService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockChallengesService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockChallengesService {
	mock := &mockChallengesService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
